name: Publish Python package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine

      - name: Create .pypirc file
        run: |
          # Remove any existing directory at ~/.pypirc (if any)
          rm -rf ~/.pypirc
          # Create the .pypirc file
          echo "[distutils]" > ~/.pypirc
          echo "index-servers =" >> ~/.pypirc
          echo "    pypi" >> ~/.pypirc
          echo "[pypi]" >> ~/.pypirc
          echo "username = ${PYPI_USERNAME}" >> ~/.pypirc
          echo "password = ${PYPI_API_TOKEN}" >> ~/.pypirc

      - name: Build distribution package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload package to PyPI
        run: |
          twine upload dist/* --verbos

      - name: Delete .pypirc file permanently
        run: |
          rm -f ~/.pypirc
